language: go
sudo: required
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install tree -y ; fi
os:
- linux
go:
- 1.7.1
install:
- make
script:
- make test
